### ISSUE TITLE
Fix html errors found by w3 validator

### ISSUE THREAD

**Issue by non-Jedi** [t3chguy/matrix-static#28]
See e.g. https://validator.w3.org/nu/?doc=https%3A%2F%2Fview.matrix.org%2Froom%2F%21cURbafjkfsMDVwdRDQ%3Amatrix.org%2F

Primary errors seem to be not including an `alt` attribute on `<img>` tags and using using `nowrap` attribute on `<td>` element is considered obsolete.

I'm not really sure *what* we should be putting as image alt-texts, but according to w3, *something* does have to be there.

**Comment by t3chguy** [comment]
Thanks! Forgot about validating:

for Logos the entity they represent, i.e MXID/Room ID
for Image thumbnails: the image body.

I believe the above is what riot-web does

Thanks for running a validator check on it

Re `nowrap`, I shall look into that

**Comment by non-Jedi** [comment]
@t3chguy did you mean to close this?

**Comment by t3chguy** [comment]
Not at all, must have pressed the wrong button
(mobile website sucks)

**Comment by t3chguy** [comment]
Alright, appropriate fixes have been made to develop branch

thanks for pointing out this issue!!
