### ISSUE TITLE
Remove code for handling unknown types in room-chat.qtpl template

### ISSUE THREAD

**Issue by non-Jedi** [t3chguy/matrix-static#41]
it looks to me like matrix-static should display "Cannot Understand Event" when it gets an event with a type it doesn't recognize, but instead, it just doesn't display that event.

**Comment by non-Jedi** [comment]
See event sent by TravisR $15036237191020krcWp:t2l.io

**Comment by t3chguy** [comment]
It could, but it's trying to match riot-web's behaviour and doesn't

**Comment by non-Jedi** [comment]
Okay. For the record, it was this from the template that made me think all events were handled. IMO, matrix-static should either just represent all events as best it can or have this code removed as the template will never see an event it doesn't understand anyway.

https://github.com/t3chguy/matrix-static/blob/8ea746526596675018cd562bdefef280d14a695c/src/github.com/t3chguy/matrix-static/templates/room-chat.qtpl#L252

**Comment by t3chguy** [comment]
Very true
Initially I didn't filter events but currently it's actually essential

**Comment by t3chguy** [comment]
Fixed by 5c796ba6cb71309810be655c2192df8cc901a5cd
